name: Pre Deploy
on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  linting:
    name: Lint
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node_version: ${{ matrix.node_version }}

      - name: run Install and Lint
        run: |
          npm ci # or yarn install
          npm run lint # or yarn lint

  # testing:
  #   if: ${{ always() }}
  #   needs: linting
  #   name: Test
  #   runs-on: ubuntu-18.04
  #   strategy:
  #     matrix:
  #       node-version: [14.x]
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Use Node.js ${{ matrix.node_version }}
  #       uses: actions/setup-node@v2
  #       with:
  #         node_version: ${{ matrix.node_version }}

  #     - name: run Install and Test
  #       run: |
  #         npm ci # or yarn install
  #         npm run test # or yarn test

  building:
    if: ${{ always() }}
    needs: [linting]
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node_version: ${{ matrix.node_version }}

      - name: run Install and Build
        run: |
          npm ci # or yarn install
          npm run build # or yarn build
  cypress-run:
    if: ${{ always() }}
    needs: [linting, building]
    name: Cypress Run
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node_version: ${{ matrix.node_version }}

      - name: run Install and Build
        run: |
          npm ci # or yarn install
      - name: Cypress run
        uses: cypress-io/github-action@v2
