name: Pre Deploy
on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  linting:
    name: Lint
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [14]
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}

      - name: run Install and Lint
        run: |
          npm install # or yarn install
          npm run lint # or yarn lint

  testing:
    if: ${{ always() }}
    needs: linting
    name: Test
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [14]
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}

      - name: run Install and Lint
        run: |
          npm install # or yarn install

      - name: run Test
        run: |
          npm run test # or yarn test

  building:
    if: ${{ always() }}
    needs: [linting, testing]
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [14]
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}

      - name: run Install and Lint
        run: |
          npm install # or yarn install

      - name: run Build
        run: |
          npm run build # or yarn build
